import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ownersCommand, upsertBlock } from "./owners.ts";

const archYaml = [
  'version: "1.0"',
  "name: Demo",
  "nodes:",
  "  - id: api",
  "    kind: service",
  "    name: API",
  "    description: x",
  "    sourcePath: src/api",
  "    owner: team-core",
  "  - id: billing",
  "    kind: worker",
  "    name: Billing",
  "    description: x",
  "    sourcePath: src/billing",
  "    owner: '@org/billing'",
  "  - id: db",
  "    kind: database",
  "    name: DB",
  "    description: x",
  "edges: []",
  "",
].join("\n");

describe("ownersCommand", () => {
  let cwd: string;
  let originalCwd: string;
  let logSpy: ReturnType<typeof vi.spyOn>;
  let errSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(async () => {
    cwd = await mkdtemp(path.join(tmpdir(), "archik-owners-"));
    await mkdir(path.join(cwd, ".archik"));
    await mkdir(path.join(cwd, "src/api"), { recursive: true });
    await mkdir(path.join(cwd, "src/billing"), { recursive: true });
    await writeFile(path.join(cwd, ".archik/main.archik.yaml"), archYaml);
    originalCwd = process.cwd();
    process.chdir(cwd);
    logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    errSpy = vi.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    logSpy.mockRestore();
    errSpy.mockRestore();
    await rm(cwd, { recursive: true, force: true });
  });

  it("writes a managed block into .github/CODEOWNERS", async () => {
    const code = await ownersCommand({ _: ["sync"] });
    expect(code).toBe(0);
    const content = await readFile(
      path.join(cwd, ".github/CODEOWNERS"),
      "utf-8",
    );
    expect(content).toContain("archik:begin");
    expect(content).toContain("/src/api/ @team-core");
    expect(content).toContain("/src/billing/ @org/billing");
    expect(content).not.toContain("db");
  });

  it("preserves hand-authored rules outside the block", async () => {
    await mkdir(path.join(cwd, ".github"), { recursive: true });
    await writeFile(
      path.join(cwd, ".github/CODEOWNERS"),
      "* @org/maintainers\n",
    );
    expect(await ownersCommand({ _: ["sync"] })).toBe(0);
    const content = await readFile(
      path.join(cwd, ".github/CODEOWNERS"),
      "utf-8",
    );
    expect(content).toContain("* @org/maintainers");
    expect(content).toContain("/src/api/ @team-core");

    // Re-sync after an owner change replaces only the block.
    await writeFile(
      path.join(cwd, ".archik/main.archik.yaml"),
      archYaml.replace("team-core", "team-platform"),
    );
    expect(await ownersCommand({ _: ["sync"] })).toBe(0);
    const updated = await readFile(
      path.join(cwd, ".github/CODEOWNERS"),
      "utf-8",
    );
    expect(updated).toContain("* @org/maintainers");
    expect(updated).toContain("@team-platform");
    expect(updated).not.toContain("@team-core");
    expect(updated.match(/archik:begin/g)).toHaveLength(1);
  });

  it("check exits 1 when stale, 0 after sync", async () => {
    expect(await ownersCommand({ _: ["check"] })).toBe(1);
    expect(await ownersCommand({ _: ["sync"] })).toBe(0);
    expect(await ownersCommand({ _: ["check"] })).toBe(0);
  });

  it("sync is idempotent", async () => {
    await ownersCommand({ _: ["sync"] });
    const before = await readFile(path.join(cwd, ".github/CODEOWNERS"), "utf-8");
    expect(await ownersCommand({ _: ["sync"] })).toBe(0);
    const after = await readFile(path.join(cwd, ".github/CODEOWNERS"), "utf-8");
    expect(after).toBe(before);
  });

  it("emits JSON shapes", async () => {
    const code = await ownersCommand({ _: ["sync"], json: "true" });
    expect(code).toBe(0);
    const parsed = JSON.parse(
      logSpy.mock.calls.map((c) => c.join(" ")).join("\n"),
    );
    expect(parsed).toMatchObject({ ok: true, rules: 2, changed: true });
  });

  it("rejects unknown subcommands", async () => {
    expect(await ownersCommand({ _: [] })).toBe(2);
  });
});

describe("upsertBlock", () => {
  it("returns null when the block already matches", () => {
    const block = "# --- archik:begin — generated by `archik owners sync`, do not edit between markers ---\n/a/ @t\n# --- archik:end ---";
    expect(upsertBlock(`intro\n\n${block}\n`, block)).toBeNull();
  });
});
