/**
 * `archik owners` — keep CODEOWNERS in step with the model. Every
 * node that declares both `owner` and `sourcePath` becomes a
 * CODEOWNERS rule, written into a clearly-marked managed block so
 * hand-authored rules outside the block are never touched.
 *
 *   archik owners sync     write/refresh the block
 *   archik owners check    exit 1 when the block is missing or stale (CI)
 *
 * The file is looked up where GitHub does (.github/CODEOWNERS,
 * CODEOWNERS, docs/CODEOWNERS); sync creates .github/CODEOWNERS when
 * none exists. Owner handles get an `@` prefix unless they already
 * carry one — keep node `owner` values aligned with your GitHub
 * team/user names for the rules to bind.
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { LoadedDoc } from "../../io/discovery.ts";
import { discoverDocs } from "../../io/discovery.ts";
import { cross, dim, tick, yellow } from "../colors.ts";
import { getString, type ParsedOptions } from "../options.ts";
import { projectRoot, resolveDocPath } from "../resolveDocPath.ts";

const BEGIN = "# --- archik:begin — generated by `archik owners sync`, do not edit between markers ---";
const END = "# --- archik:end ---";

const CODEOWNERS_LOCATIONS = [
  ".github/CODEOWNERS",
  "CODEOWNERS",
  "docs/CODEOWNERS",
];

const isJson = (opts: ParsedOptions): boolean => {
  const v = getString(opts, "json");
  return v !== undefined && v !== "false" && v !== "0";
};

/** One rule per owned node, sorted by path for stable diffs. A
 *  directory sourcePath gets a trailing slash so the rule covers the
 *  subtree the way GitHub expects. */
export function buildCodeownersLines(docs: LoadedDoc[]): string[] {
  const rules = new Map<string, string>(); // path pattern → handle
  for (const { doc } of docs) {
    for (const node of doc.nodes) {
      if (node.owner === undefined || node.sourcePath === undefined) continue;
      const handle = node.owner.startsWith("@")
        ? node.owner
        : `@${node.owner}`;
      const last = node.sourcePath.split("/").pop() ?? "";
      const isFile = /\.[^./]+$/.test(last);
      const pattern = `/${node.sourcePath}${isFile ? "" : "/"}`;
      rules.set(pattern, handle);
    }
  }
  return [...rules.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([pattern, handle]) => `${pattern} ${handle}`);
}

function renderBlock(lines: string[]): string {
  return [BEGIN, ...lines, END].join("\n");
}

/** Replace the managed block in `current`, or append one. Returns
 *  null when `current` already contains exactly this block. */
export function upsertBlock(current: string, block: string): string | null {
  const beginIdx = current.indexOf(BEGIN);
  const endIdx = current.indexOf(END);
  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const existing = current.slice(beginIdx, endIdx + END.length);
    if (existing === block) return null;
    return current.slice(0, beginIdx) + block + current.slice(endIdx + END.length);
  }
  const sep = current === "" || current.endsWith("\n") ? "" : "\n";
  return `${current}${sep}${current === "" ? "" : "\n"}${block}\n`;
}

export async function ownersCommand(opts: ParsedOptions): Promise<number> {
  const sub = opts._[0];
  const json = isJson(opts);
  if (sub !== "sync" && sub !== "check") {
    console.error(`${cross()} Usage: archik owners sync | check [--json]`);
    return 2;
  }

  let abs: string;
  try {
    abs = await resolveDocPath(getString(opts, "doc"));
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (json) console.log(JSON.stringify({ ok: false, error: message }));
    else console.error(`${cross()} ${message}`);
    return 2;
  }
  const root = projectRoot(abs);
  const discovery = await discoverDocs(abs, root);
  const rootError = discovery.errors.find((e) => e.abs === abs);
  if (rootError !== undefined) {
    if (json) console.log(JSON.stringify({ ok: false, error: rootError.message }));
    else console.error(`${cross()} ${rootError.relPath}: ${rootError.message}`);
    return 2;
  }

  const lines = buildCodeownersLines(discovery.docs);
  const block = renderBlock(lines);

  const existingRel = CODEOWNERS_LOCATIONS.find((rel) =>
    existsSync(path.resolve(root, rel)),
  );
  const targetRel = existingRel ?? ".github/CODEOWNERS";
  const targetAbs = path.resolve(root, targetRel);
  const current = existingRel !== undefined
    ? await readFile(targetAbs, "utf-8")
    : "";

  const next = upsertBlock(current, block);
  const inSync = next === null;

  if (sub === "check") {
    if (json) {
      console.log(
        JSON.stringify(
          { ok: inSync, file: targetRel, rules: lines.length },
          null,
          2,
        ),
      );
    } else if (inSync) {
      console.log(`${tick()} ${targetRel} — archik block up to date (${lines.length} rule${lines.length === 1 ? "" : "s"})`);
    } else {
      console.error(
        `${cross()} ${targetRel} is ${existingRel === undefined ? "missing" : "stale"} — run \`archik owners sync\``,
      );
    }
    return inSync ? 0 : 1;
  }

  // sync
  if (lines.length === 0) {
    const msg = "no nodes declare both `owner` and `sourcePath` — nothing to sync";
    if (json) console.log(JSON.stringify({ ok: true, file: targetRel, rules: 0, note: msg }));
    else console.log(`${yellow("~")} ${msg}`);
    return 0;
  }
  if (inSync) {
    if (json) console.log(JSON.stringify({ ok: true, file: targetRel, rules: lines.length, changed: false }));
    else console.log(`${tick()} ${targetRel} already up to date (${lines.length} rule${lines.length === 1 ? "" : "s"})`);
    return 0;
  }
  await mkdir(path.dirname(targetAbs), { recursive: true });
  await writeFile(targetAbs, next, "utf-8");
  if (json) {
    console.log(JSON.stringify({ ok: true, file: targetRel, rules: lines.length, changed: true }));
  } else {
    console.log(`${tick()} ${targetRel} — ${lines.length} rule${lines.length === 1 ? "" : "s"} synced from node owners`);
    console.log(dim(`  rules bind when node \`owner\` values match GitHub team/user handles`));
  }
  return 0;
}
